runtime: nodejs20  # Ensure you're using Node.js 20 (or latest)
service: chatbotdemo

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /
    static_dir: dist
